language: node_js
node_js:
  - 'stable'

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  api_key:
    secure: $bloft
  strategy: git
  app:
    master: portfolio-one
  run:
    - restart
